- hosts: web
  remote_user: root
  become: yes
  vars: 
    packages:
      - httpd
      - nano
      - mysql
  tasks: 
  - name: install software
    yum: 
      name: "{{ item }}"
      state: installed
    loop: "{{ packages }}"
  - name: remove software
    yum: 
      name: "{{ item }}"
      state: removed
    loop:  "{{ packages }}"